import {
  CipherSuite,
  ClientId,
  ConversationId,
  CoreCrypto,
  Credential,
  Database,
  DatabaseKey,
  DeviceId,
  Uuid,
  Welcome,
  initWasmModule
} from "@wireapp/core-crypto/browser";

const SUITE = CipherSuite.Mls128Dhkemx25519Aes128gcmSha256Ed25519;
const WASM_URL = new URL(
  "../../node_modules/@wireapp/core-crypto/dist/browser/autogenerated/wasm-bindgen/index_bg.wasm",
  import.meta.url
).href;
const encoder = new TextEncoder();
const decoder = new TextDecoder();

function randomBytes(length) {
  return crypto.getRandomValues(new Uint8Array(length));
}

async function createMlsClient(uuid, deviceHex) {
  const database = await Database.inMemory(new DatabaseKey(randomBytes(32)));
  const core = CoreCrypto.new(database);
  const clientId = new ClientId(new Uuid(uuid), DeviceId.fromHexString(deviceHex), "browser.test.invalid");
  const commits = [];
  const transport = {
    async sendCommitBundle(bundle) {
      commits.push(bundle);
    },
    async prepareForTransport() {
      throw new Error("history-secret transport must stay disabled");
    }
  };
  await core.transaction(ctx => ctx.mlsInit(clientId, transport));
  const credentialRef = await core.transaction(ctx => ctx.addCredential(Credential.basic(SUITE, clientId)));
  return { database, core, clientId, credentialRef, commits };
}

async function decryptText(client, conversationId, ciphertext) {
  const result = await client.core.transaction(ctx => ctx.decryptMessage(conversationId, ciphertext));
  return decoder.decode(result.message);
}

window.runMlsInterop = async function runMlsInterop() {
  await initWasmModule(WASM_URL);
  const alice = await createMlsClient("00000000-0000-4000-8000-000000000001", "0000000000000001");
  const bob = await createMlsClient("00000000-0000-4000-8000-000000000002", "0000000000000002");
  const conversationId = new ConversationId(randomBytes(32));
  try {
    const bobPackage = await bob.core.transaction(ctx => ctx.generateKeyPackage(bob.credentialRef, 3600));
    await alice.core.transaction(ctx => ctx.createConversation(conversationId, alice.credentialRef));
    await alice.core.transaction(ctx => ctx.addClientsToConversation(conversationId, [bobPackage]));
    const addBundle = alice.commits.shift();
    if (!addBundle?.welcome) throw new Error("add commit did not produce Welcome");
    await bob.core.transaction(ctx => ctx.processWelcomeMessage(new Welcome(addBundle.welcome.serialize())));

    const firstCiphertext = await alice.core.transaction(ctx => ctx.encryptMessage(conversationId, encoder.encode("alice-to-bob")));
    if (await decryptText(bob, conversationId, firstCiphertext) !== "alice-to-bob") {
      throw new Error("Alice to Bob decryption mismatch");
    }
    const replyCiphertext = await bob.core.transaction(ctx => ctx.encryptMessage(conversationId, encoder.encode("bob-to-alice")));
    if (await decryptText(alice, conversationId, replyCiphertext) !== "bob-to-alice") {
      throw new Error("Bob to Alice decryption mismatch");
    }

    await alice.core.transaction(ctx => ctx.updateKeyingMaterial(conversationId));
    const updateBundle = alice.commits.shift();
    if (!updateBundle?.commit) throw new Error("self-update commit missing");
    await bob.core.transaction(ctx => ctx.decryptMessage(conversationId, updateBundle.commit));
    const aliceEpoch = Number(await alice.core.transaction(ctx => ctx.conversationEpoch(conversationId)));
    const bobEpoch = Number(await bob.core.transaction(ctx => ctx.conversationEpoch(conversationId)));
    if (aliceEpoch !== bobEpoch || aliceEpoch < 2) throw new Error("MLS epochs diverged after self-update");

    const tamperTarget = await alice.core.transaction(ctx => ctx.encryptMessage(conversationId, encoder.encode("authenticated")));
    const tampered = new Uint8Array(tamperTarget);
    tampered[tampered.length - 1] ^= 1;
    let tamperRejected = false;
    try {
      await bob.core.transaction(ctx => ctx.decryptMessage(conversationId, tampered));
    } catch {
      tamperRejected = true;
    }
    if (!tamperRejected) throw new Error("tampered MLS ciphertext was accepted");
    if (await decryptText(bob, conversationId, tamperTarget) !== "authenticated") {
      throw new Error("valid ciphertext failed after tamper rejection");
    }
    let replayRejected = false;
    try {
      await bob.core.transaction(ctx => ctx.decryptMessage(conversationId, tamperTarget));
    } catch {
      replayRejected = true;
    }
    if (!replayRejected) throw new Error("replayed MLS ciphertext was accepted");

    const aliceRoster = await alice.core.transaction(ctx => ctx.getClientIds(conversationId));
    const bobRoster = await bob.core.transaction(ctx => ctx.getClientIds(conversationId));
    if (aliceRoster.length !== 2 || bobRoster.length !== 2) throw new Error("MLS roster mismatch");
    return {
      ok: true,
      epoch: aliceEpoch,
      rosterSize: aliceRoster.length,
      tamperRejected,
      replayRejected
    };
  } finally {
    await alice.database.close();
    await bob.database.close();
  }
};

document.querySelector("#status").textContent = "fixture-loaded";
