const crypto = require("crypto");
const fs = require("fs");
const path = require("path");
const { test, expect } = require("@playwright/test");

test("CoreCrypto performs two-device MLS add, messaging, update, tamper and replay checks", async ({ page }) => {
  await page.goto("/test/production/fixture.html");
  await expect(page.locator("#status")).toHaveText("production-fixture-loaded");
  const result = await page.evaluate(() => window.runMlsInterop());
  expect(result).toEqual({
    ok: true,
    epoch: 2,
    rosterSize: 2,
    tamperRejected: true,
    replayRejected: true
  });
});

test("production bundle opens and reopens persistent CoreCrypto IndexedDB after parallel WASM initialization", async ({ page }) => {
  await page.goto("/test/production/fixture.html");
  const wasmUrl = await page.evaluate(() => window.getProductionWasmUrl());
  const wasm = await page.request.get(wasmUrl);
  expect(wasm.ok()).toBeTruthy();
  expect(wasm.headers()["content-type"]).toContain("application/wasm");
  const publishedHash = crypto.createHash("sha256").update(await wasm.body()).digest("hex");
  const packageWasm = fs.readFileSync(path.resolve(
    __dirname,
    "../../node_modules/@wireapp/core-crypto/dist/browser/autogenerated/wasm-bindgen/index_bg.wasm"
  ));
  expect(publishedHash).toBe(crypto.createHash("sha256").update(packageWasm).digest("hex"));
  const result = await page.evaluate(() => window.runPersistentDatabaseProbe({ concurrentInit: true }));
  expect(result.ok).toBe(true);
  expect(result.memoryCoreCreated).toBe(true);
  expect(result.firstLocation).toBe(result.secondLocation);
  expect(await page.evaluate(() => window.getDatabaseRepairPolicy())).toEqual({
    unregisteredEarlyFailure: true,
    registeredEarlyFailure: false,
    unregisteredLateFailure: false
  });
});

test("production application bundle contains MLS v4 paths and no legacy private-key APIs", async ({ page }) => {
  const index = await page.request.get("/");
  expect(index.ok()).toBeTruthy();
  const html = await index.text();
  const scripts = [...html.matchAll(/<script[^>]+src="([^"]+)"/g)].map(match => match[1]);
  expect(scripts.length).toBeGreaterThan(0);
  const sources = await Promise.all(scripts.map(async source => {
    const response = await page.request.get(source);
    expect(response.ok()).toBeTruthy();
    return response.text();
  }));
  const bundle = sources.join("\n");
  expect(bundle).toContain("/crypto/v4/");
  expect(bundle).not.toMatch(/\/e2ee\/(?:identity(?:-backup)?|conversations\/[^"']+\/key)/);
});
