import {
  CipherSuite,
  ClientId,
  ConversationId,
  CoreCrypto,
  Credential,
  Database,
  DatabaseKey,
  DeviceId,
  Uuid,
  Welcome
} from "@wireapp/core-crypto/browser";
import { initializeCoreCryptoRuntime } from "../../src/crypto/coreCryptoRuntime";
import React, { useEffect } from "react";
import { createRoot } from "react-dom/client";
import CryptoGate from "../../src/crypto/CryptoGate";
import SecureTransitionGate from "../../src/crypto/SecureTransitionGate";
import useSecureTransition from "../../src/hooks/useSecureTransition";
import { shouldAutomaticallyRepairDatabase } from "../../src/crypto/mls/databaseStorage";
import "../../src/App.css";

const SUITE = CipherSuite.Mls128Dhkemx25519Aes128gcmSha256Ed25519;
const WASM_URL = new URL(
  "../../node_modules/@wireapp/core-crypto/dist/browser/autogenerated/wasm-bindgen/index_bg.wasm",
  import.meta.url
).href;
const encoder = new TextEncoder();
const decoder = new TextDecoder();

function randomBytes(length) {
  return crypto.getRandomValues(new Uint8Array(length));
}

function deleteDatabase(name) {
  return new Promise((resolve, reject) => {
    const request = indexedDB.deleteDatabase(name);
    request.onsuccess = () => resolve();
    request.onerror = () => reject(request.error || new Error("database deletion failed"));
    request.onblocked = () => reject(new Error("database deletion blocked"));
  });
}

async function createMlsClient(uuid, deviceHex) {
  const database = await Database.inMemory(new DatabaseKey(randomBytes(32)));
  const core = CoreCrypto.new(database);
  const clientId = new ClientId(new Uuid(uuid), DeviceId.fromHexString(deviceHex), "browser.test.invalid");
  const commits = [];
  const transport = {
    async sendCommitBundle(bundle) { commits.push(bundle); },
    async prepareForTransport() { throw new Error("history-secret transport must stay disabled"); }
  };
  await core.transaction(ctx => ctx.mlsInit(clientId, transport));
  const credentialRef = await core.transaction(ctx => ctx.addCredential(Credential.basic(SUITE, clientId)));
  return { database, core, clientId, credentialRef, commits };
}

async function decryptText(client, conversationId, ciphertext) {
  const result = await client.core.transaction(ctx => ctx.decryptMessage(conversationId, ciphertext));
  return decoder.decode(result.message);
}

window.getProductionWasmUrl = () => WASM_URL;
window.getDatabaseRepairPolicy = () => ({
  unregisteredEarlyFailure: shouldAutomaticallyRepairDatabase("database-open", null),
  registeredEarlyFailure: shouldAutomaticallyRepairDatabase("database-open", { status: "active" }),
  unregisteredLateFailure: shouldAutomaticallyRepairDatabase("device-register", null)
});

window.runPersistentDatabaseProbe = async function runPersistentDatabaseProbe({ concurrentInit = false } = {}) {
  const name = `liotan-production-probe-${crypto.randomUUID()}`;
  const concurrentName = `${name}-parallel`;
  const keyBytes = randomBytes(32);
  const concurrentKeyBytes = randomBytes(32);
  try {
    if (!concurrentInit) await initializeCoreCryptoRuntime();
    const openAfterInit = async (databaseName, bytes) => {
      await initializeCoreCryptoRuntime();
      return Database.open(databaseName, new DatabaseKey(bytes));
    };
    const [first, concurrent] = concurrentInit
      ? await Promise.all([
          openAfterInit(name, keyBytes),
          openAfterInit(concurrentName, concurrentKeyBytes)
        ])
      : [await Database.open(name, new DatabaseKey(keyBytes)), null];
    if (concurrent) await concurrent.close();
    const memory = await Database.inMemory(new DatabaseKey(randomBytes(32)));
    const memoryCore = CoreCrypto.new(memory);
    await memory.close();
    const firstLocation = await first.getLocation();
    CoreCrypto.new(first);
    await first.close();
    const reopened = await Database.open(name, new DatabaseKey(keyBytes));
    const secondLocation = await reopened.getLocation();
    CoreCrypto.new(reopened);
    await reopened.close();
    return {
      ok: true,
      memoryCoreCreated: Boolean(memoryCore),
      firstLocation,
      secondLocation
    };
  } finally {
    keyBytes.fill(0);
    concurrentKeyBytes.fill(0);
    await deleteDatabase(name).catch(() => {});
    await deleteDatabase(concurrentName).catch(() => {});
  }
};

window.runMlsInterop = async function runMlsInterop() {
  await initializeCoreCryptoRuntime();
  const alice = await createMlsClient("00000000-0000-4000-8000-000000000001", "0000000000000001");
  const bob = await createMlsClient("00000000-0000-4000-8000-000000000002", "0000000000000002");
  const conversationId = new ConversationId(randomBytes(32));
  try {
    const bobPackage = await bob.core.transaction(ctx => ctx.generateKeyPackage(bob.credentialRef, 3600));
    await alice.core.transaction(ctx => ctx.createConversation(conversationId, alice.credentialRef));
    await alice.core.transaction(ctx => ctx.addClientsToConversation(conversationId, [bobPackage]));
    const addBundle = alice.commits.shift();
    if (!addBundle?.welcome) throw new Error("add commit did not produce Welcome");
    await bob.core.transaction(ctx => ctx.processWelcomeMessage(new Welcome(addBundle.welcome.serialize())));
    const ciphertext = await alice.core.transaction(ctx => ctx.encryptMessage(conversationId, encoder.encode("production-mls")));
    if (await decryptText(bob, conversationId, ciphertext) !== "production-mls") throw new Error("MLS mismatch");
    const reply = await bob.core.transaction(ctx => ctx.encryptMessage(conversationId, encoder.encode("production-reply")));
    if (await decryptText(alice, conversationId, reply) !== "production-reply") throw new Error("MLS reply mismatch");
    await alice.core.transaction(ctx => ctx.updateKeyingMaterial(conversationId));
    const updateBundle = alice.commits.shift();
    await bob.core.transaction(ctx => ctx.decryptMessage(conversationId, updateBundle.commit));
    const epoch = Number(await alice.core.transaction(ctx => ctx.conversationEpoch(conversationId)));
    const tamperTarget = await alice.core.transaction(ctx => ctx.encryptMessage(conversationId, encoder.encode("authenticated")));
    const tampered = new Uint8Array(tamperTarget);
    tampered[tampered.length - 1] ^= 1;
    let tamperRejected = false;
    try { await bob.core.transaction(ctx => ctx.decryptMessage(conversationId, tampered)); } catch { tamperRejected = true; }
    if (!tamperRejected || await decryptText(bob, conversationId, tamperTarget) !== "authenticated") {
      throw new Error("MLS tamper handling mismatch");
    }
    let replayRejected = false;
    try { await bob.core.transaction(ctx => ctx.decryptMessage(conversationId, tamperTarget)); } catch { replayRejected = true; }
    const roster = await alice.core.transaction(ctx => ctx.getClientIds(conversationId));
    return { ok: true, epoch, rosterSize: roster.length, tamperRejected, replayRejected };
  } finally {
    await alice.database.close();
    await bob.database.close();
  }
};

function TransitionHarness() {
  const transition = useSecureTransition();
  useEffect(() => { transition.completeSecureTransition({ minimumMs: 0 }); }, []);

  async function run(kind) {
    if (kind === "logout") {
      transition.beginSecureTransition("closing-session", { minimumMs: 80 });
      await new Promise(resolve => setTimeout(resolve, 20));
      await transition.completeSecureTransition();
      return;
    }
    transition.beginSecureTransition("checking-session", { minimumMs: 100 });
    await new Promise(resolve => setTimeout(resolve, 20));
    transition.updateSecureTransition("opening-storage");
    await new Promise(resolve => setTimeout(resolve, 20));
    transition.updateSecureTransition("preparing-messages");
    await transition.completeSecureTransition();
  }

  return <>
    <button data-action="login" onClick={() => run("login")}>login</button>
    <button data-action="register" onClick={() => run("register")}>register</button>
    <button data-action="logout" onClick={() => run("logout")}>logout</button>
    <SecureTransitionGate active={transition.secureTransition.active} stage={transition.secureTransition.stage} />
  </>;
}

window.mountTransitionHarness = function mountTransitionHarness() {
  createRoot(document.querySelector("#root")).render(<TransitionHarness />);
};

window.mountFailingCryptoGate = function mountFailingCryptoGate() {
  const storageError = Object.assign(new Error("technical detail must not reach the user"), {
    code: "registered-storage-unavailable",
    reprovisionRequired: true
  });
  const services = {
    loadRecoveryKey: async () => "A".repeat(43),
    initializeMlsEngine: async () => { throw storageError; },
    cryptoBootstrap: async () => { throw new Error("unexpected bootstrap"); },
    createRecoveryKey: () => "",
    saveRecoveryKey: async () => {},
    normalizeRecoveryKey: () => ({ encoded: "", bytes: new Uint8Array(32) }),
    reprovisionMlsDevice: async () => {}
  };
  createRoot(document.querySelector("#root")).render(
    <CryptoGate username="fixture-user" cryptoServices={services} onBlocked={async () => {}}>
      <div id="messenger-sentinel">messenger must stay blocked</div>
    </CryptoGate>
  );
};

document.querySelector("#status").textContent = "production-fixture-loaded";
