import {
  CipherSuite,
  ConversationId,
  CoreCrypto,
  Credential,
  Database,
  DatabaseKey,
  Welcome
} from "@wireapp/core-crypto/browser";
import { initializeCoreCryptoRuntime } from "../../src/crypto/coreCryptoRuntime";
import { deriveAccountKeys, signCanonical } from "../../src/crypto/accountKeys";
import {
  buildDirectoryMutation,
  directoryDeviceCommitment
} from "../../src/crypto/mls/directory";
import { verifyAndPinAccountDirectory } from "../../src/crypto/mls/trust";
import {
  reconcileSyncCursor,
  validateRecipientEventPage
} from "../../src/crypto/mls/syncCursor";
import {
  bytesToBase64Url,
  canonicalJson,
  sha256Base64Url
} from "../../src/crypto/encoding";
import { createInitializedClientIdentity } from "../../src/crypto/mls/identifiers";
import { assertEnvelopeSchema } from "../../src/crypto/mls/envelope";
import { encryptAndUploadMedia } from "../../src/crypto/mls/media";
import {
  BACKGROUND_MAINTENANCE_INTERVAL_MS,
  MEDIA_MAGIC,
  SELF_UPDATE_INTERVAL_MS
} from "../../src/crypto/mls/constants";
import { destroyUniffi } from "../../src/crypto/mls/uniffiLifecycle";
import {
  createRecoveryKey,
  disableRecoveryProtection,
  enableRecoveryProtection,
  getRecoveryProtectionStatus,
  getEncryptedHistoryRecord,
  listEncryptedRecords,
  listEncryptedHistoryRecords,
  loadRecoveryKey,
  migrateEncryptedHistoryRecords,
  putEncryptedHistoryRecord,
  putEncryptedRecords,
  saveRecoveryKey
} from "../../src/crypto/recoveryStore";
import React, { useEffect } from "react";
import { createRoot } from "react-dom/client";
import CryptoGate from "../../src/crypto/CryptoGate";
import SecureTransitionGate from "../../src/crypto/SecureTransitionGate";
import AttachmentDraftModal from "../../src/components/chat/AttachmentDraftModal";
import UserProfileModal from "../../src/components/modals/UserProfileModal";
import ChatSecurityNotice from "../../src/components/chat/ChatSecurityNotice";
import SafetyNumberModal from "../../src/components/chat/SafetyNumberModal";
import DevicesPage from "../../src/components/settings/pages/DevicesPage";
import LiotanIcon from "../../src/components/common/LiotanIcon";
import useSecureTransition from "../../src/hooks/useSecureTransition";
import { shouldAutomaticallyRepairDatabase } from "../../src/crypto/mls/databaseStorage";
import { computeSafetyNumber } from "../../src/crypto/mlsEngine";
import "../../src/App.css";

const SUITE = CipherSuite.Mls128Dhkemx25519Aes128gcmSha256Ed25519;
const WASM_URL = new URL(
  "../../node_modules/@wireapp/core-crypto/dist/browser/autogenerated/wasm-bindgen/index_bg.wasm",
  import.meta.url
).href;
const encoder = new TextEncoder();
const decoder = new TextDecoder();

function randomBytes(length) {
  return crypto.getRandomValues(new Uint8Array(length));
}

function deleteDatabase(name) {
  return new Promise((resolve, reject) => {
    const request = indexedDB.deleteDatabase(name);
    request.onsuccess = () => resolve();
    request.onerror = () => reject(request.error || new Error("database deletion failed"));
    request.onblocked = () => reject(new Error("database deletion blocked"));
  });
}

async function createMlsClient(uuid, deviceHex) {
  const databaseKey = new DatabaseKey(randomBytes(32));
  let database;
  try {
    database = await Database.inMemory(databaseKey);
  } finally {
    destroyUniffi(databaseKey);
  }
  const core = CoreCrypto.new(database);
  const { clientId } = await createInitializedClientIdentity({
    cryptoUserId: uuid,
    deviceId: deviceHex,
    domain: "browser.test.invalid"
  });
  const commits = [];
  const transport = {
    async sendCommitBundle(bundle) { commits.push(bundle); },
    async prepareForTransport() { throw new Error("history-secret transport must stay disabled"); }
  };
  await core.transaction(ctx => ctx.mlsInit(clientId, transport));
  const credential = Credential.basic(SUITE, clientId);
  let credentialRef;
  try {
    credentialRef = await core.transaction(ctx => ctx.addCredential(credential));
  } finally {
    destroyUniffi(credential);
  }
  return { database, core, clientId, credentialRef, commits };
}

async function closeMlsClient(client) {
  destroyUniffi(client.credentialRef);
  destroyUniffi(client.clientId);
  destroyUniffi(client.core);
  await client.database.close();
  destroyUniffi(client.database);
}

async function decryptText(client, conversationId, ciphertext) {
  const result = await client.core.transaction(ctx => ctx.decryptMessage(conversationId, ciphertext));
  return decoder.decode(result.message);
}

window.getProductionWasmUrl = () => WASM_URL;
window.runColdStartClientIdentityProbe = async function runColdStartClientIdentityProbe() {
  const expected = "00000000-0000-4000-8000-000000000009:0000000000000009@browser.test.invalid";
  const identity = await createInitializedClientIdentity({
    cryptoUserId: "00000000-0000-4000-8000-000000000009",
    deviceId: "0000000000000009",
    domain: "browser.test.invalid"
  });
  try {
    return { ok: true, clientId: identity.clientIdString, matches: identity.clientIdString === expected };
  } finally {
    destroyUniffi(identity.clientId);
  }
};
window.createProductionRecoveryKey = () => createRecoveryKey();
window.saveProductionRecoveryKey = (username, key) => saveRecoveryKey(username, key);
window.loadProductionRecoveryKey = username => loadRecoveryKey(username);
window.runRecoveryProtectionProbe = async function runRecoveryProtectionProbe() {
  const username = `protected-${crypto.randomUUID()}`;
  const recoveryKey = createRecoveryKey();
  const passphrase = `local-${crypto.randomUUID()}`;
  await saveRecoveryKey(username, recoveryKey);
  await enableRecoveryProtection(username, passphrase);
  const protectedStatus = await getRecoveryProtectionStatus(username);
  let presenceRequired = false;
  try { await loadRecoveryKey(username); } catch (error) {
    presenceRequired = error?.code === "recovery-user-presence-required";
  }
  let wrongRejected = false;
  try { await loadRecoveryKey(username, { passphrase: "definitely-wrong-passphrase" }); } catch (error) {
    wrongRejected = error?.code === "recovery-unlock-failed";
  }
  const unlocked = await Promise.all([
    loadRecoveryKey(username, { passphrase }),
    loadRecoveryKey(username, { passphrase })
  ]);
  const db = await new Promise((resolve, reject) => {
    const request = indexedDB.open("liotan-local-crypto-v4", 2);
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(request.error);
  });
  let serializedRecord = "";
  try {
    const record = await new Promise((resolve, reject) => {
      const transaction = db.transaction("records", "readwrite");
      const store = transaction.objectStore("records");
      const request = store.get(`recovery:${username}`);
      request.onsuccess = () => {
        serializedRecord = JSON.stringify(request.result);
        store.put(request.result, `recovery-migration:${username}`);
        store.delete(`recovery:${username}`);
      };
      transaction.oncomplete = () => resolve(request.result);
      transaction.onerror = () => reject(transaction.error);
    });
    if (!record) throw new Error("protected record missing");
  } finally {
    db.close();
  }
  const resumed = await loadRecoveryKey(username, { passphrase });
  const resumedStatus = await getRecoveryProtectionStatus(username);
  await disableRecoveryProtection(username, passphrase);
  const unprotected = await loadRecoveryKey(username);
  return {
    protected: protectedStatus.requiresUserPresence,
    presenceRequired,
    wrongRejected,
    concurrentUnlock: unlocked.every(value => value === recoveryKey),
    dumpContainsRecoveryKey: serializedRecord.includes(recoveryKey),
    resumed: resumed === recoveryKey && !resumedStatus.migrationPending,
    disabled: unprotected === recoveryKey
  };
};
window.runEncryptedHistoryPagingProbe = async function runEncryptedHistoryPagingProbe() {
  const conversationId = `history-${crypto.randomUUID()}`;
  const cacheKey = randomBytes(32);
  try {
    for (let sequence = 1; sequence <= 5; sequence += 1) {
      const clientMessageId = `00000000-0000-4000-8000-${String(sequence).padStart(12, "0")}`;
      await putEncryptedHistoryRecord({ conversationId, sequence, clientMessageId }, {
        sequence,
        envelope: { clientMessageId, kind: "message", text: `message-${sequence}` }
      }, cacheKey);
    }
    const latest = await listEncryptedHistoryRecords(conversationId, cacheKey, { limit: 2 });
    const older = await listEncryptedHistoryRecords(conversationId, cacheKey, { beforeSequence: 4, limit: 2 });
    const newer = await listEncryptedHistoryRecords(conversationId, cacheKey, { afterSequence: 2, limit: 2 });
    const exactId = "00000000-0000-4000-8000-000000000004";
    const exact = await getEncryptedHistoryRecord(conversationId, exactId, cacheKey);
    return {
      latest: latest.map(record => record.sequence),
      older: older.map(record => record.sequence),
      newer: newer.map(record => record.sequence),
      exact: exact?.sequence || 0
    };
  } finally {
    cacheKey.fill(0);
  }
};
window.runAdaptiveMediaDescriptorProbe = function runAdaptiveMediaDescriptorProbe() {
  const accepted = [];
  for (const chunkSize of [256 * 1024, 512 * 1024, 1024 * 1024]) {
    const originalSize = chunkSize + 1;
    const chunks = 2;
    const messageId = crypto.randomUUID();
    const envelope = {
      v: 1,
      kind: "message",
      conversationId: crypto.randomUUID(),
      clientMessageId: messageId,
      senderUsername: "fixture-user",
      senderClientId: "fixture-client@example.test",
      sentAt: new Date().toISOString(),
      text: "",
      attachment: {
        v: 1,
        conversationId: "",
        messageId,
        uploadId: "A".repeat(24),
        bindingId: "B".repeat(24),
        ciphertextHash: "C".repeat(43),
        key: "D".repeat(43),
        deleteToken: "F".repeat(43),
        noncePrefix: "E".repeat(11),
        chunkSize,
        chunks,
        ciphertextBytes: MEDIA_MAGIC.length + chunks * (chunkSize + 16),
        original: {
          name: "fixture.bin",
          type: "file",
          mimeType: "application/octet-stream",
          size: originalSize,
          duration: 0,
          waveform: [],
          width: 0,
          height: 0
        }
      },
      replyTo: null
    };
    envelope.attachment.conversationId = envelope.conversationId;
    assertEnvelopeSchema(envelope);
    accepted.push(chunkSize);
  }
  return accepted;
};
window.runLargeMediaEncryptionProbe = async function runLargeMediaEncryptionProbe() {
  const size = 100 * 1024 * 1024;
  const file = new File([new Uint8Array(size)], "fixture-large.bin", { type: "application/octet-stream" });
  const progressStages = new Set();
  let uploadedBytes = 0;
  const result = await encryptAndUploadMedia(
    { conversationId: crypto.randomUUID() },
    file,
    crypto.randomUUID(),
    {
      onProgress: event => progressStages.add(event.stage),
      uploadRequest: async (_path, request) => {
        const attachment = request.formData.get("attachment");
        uploadedBytes = attachment.size;
        return {
          uploadId: "A".repeat(24),
          uploadCommitToken: "B".repeat(43),
          uploadDeleteToken: "C".repeat(43)
        };
      }
    }
  );
  let opfsTemporaryFiles = 0;
  if (navigator.storage?.getDirectory) {
    const root = await navigator.storage.getDirectory();
    for await (const name of root.keys()) {
      if (name.startsWith("liotan-media-") && name.endsWith(".ciphertext")) opfsTemporaryFiles += 1;
    }
  }
  return {
    originalBytes: result.descriptor.original.size,
    ciphertextBytes: result.descriptor.ciphertextBytes,
    uploadedBytes,
    chunks: result.descriptor.chunks,
    progress: [...progressStages].sort(),
    opfsTemporaryFiles
  };
};

window.runAbortedMediaCleanupProbe = async function runAbortedMediaCleanupProbe() {
  let rejected = false;
  try {
    await encryptAndUploadMedia(
      { conversationId: crypto.randomUUID() },
      new File([new Uint8Array(2 * 1024 * 1024)], "fixture-abort.bin"),
      crypto.randomUUID(),
      { uploadRequest: async () => { throw new DOMException("aborted", "AbortError"); } }
    );
  } catch (error) {
    rejected = error?.name === "AbortError";
  }
  let opfsTemporaryFiles = 0;
  if (navigator.storage?.getDirectory) {
    const root = await navigator.storage.getDirectory();
    for await (const name of root.keys()) {
      if (name.startsWith("liotan-media-") && name.endsWith(".ciphertext")) opfsTemporaryFiles += 1;
    }
  }
  return { rejected, opfsTemporaryFiles };
};
window.runDirectoryRollbackProbe = async function runDirectoryRollbackProbe() {
  const cryptoUserId = crypto.randomUUID();
  const username = `directory-${crypto.randomUUID()}`;
  const deviceId = "0000000000000011";
  const recoveryKey = bytesToBase64Url(randomBytes(32));
  const keys = await deriveAccountKeys(recoveryKey, cryptoUserId, deviceId);
  try {
    const rootPublicKey = bytesToBase64Url(keys.rootPublicKey);
    const genesis = sha256Base64Url(canonicalJson([
      "liotan-device-directory-genesis-v1",
      cryptoUserId,
      rootPublicKey
    ]));
    const baseIdentity = {
      cryptoUserId,
      rootPublicKey,
      rootFingerprint: sha256Base64Url(keys.rootPublicKey),
      directory: { version: 0, hash: genesis, statement: null, signature: "", firstContact: true },
      directoryLog: []
    };
    const manifest = {
      v: 1,
      cryptoUserId,
      username,
      deviceId,
      clientId: `${cryptoUserId}:${deviceId}@browser.test.invalid`,
      requestPublicKey: bytesToBase64Url(keys.requestPublicKey),
      credentialThumbprint: bytesToBase64Url(randomBytes(32)),
      createdAt: new Date().toISOString(),
      expiresAt: new Date(Date.now() + 86400000).toISOString()
    };
    const manifestSignature = await signCanonical(
      keys.rootSecretKey,
      "liotan-device-manifest-v1",
      manifest
    );
    const device = {
      deviceId,
      clientId: manifest.clientId,
      requestPublicKey: manifest.requestPublicKey,
      credentialThumbprint: manifest.credentialThumbprint,
      manifest,
      manifestSignature,
      status: "active",
      activationMode: "initial"
    };
    const engine = { username, keys, bootstrap: { identity: baseIdentity } };
    const first = await buildDirectoryMutation(engine, {
      devices: [],
      nextDevice: device,
      action: "register-device",
      targetDeviceId: deviceId
    });
    const firstHash = sha256Base64Url(canonicalJson([
      "liotan-device-directory-v1",
      first.statement,
      first.signature
    ]));
    const firstEntry = {
      version: 1,
      previousHash: genesis,
      hash: firstHash,
      statement: first.statement,
      signature: first.signature
    };
    const identityV1 = {
      ...baseIdentity,
      directory: {
        version: 1,
        hash: firstHash,
        statement: first.statement,
        signature: first.signature,
        firstContact: false
      },
      directoryLog: [firstEntry]
    };
    await verifyAndPinAccountDirectory(engine, {
      username,
      identity: identityV1,
      deviceCommitments: [directoryDeviceCommitment(device)],
      allDevices: [device]
    });
    engine.bootstrap.identity = identityV1;
    const second = await buildDirectoryMutation(engine, {
      devices: [device],
      nextDevice: device,
      action: "renew-device",
      targetDeviceId: deviceId
    });
    const secondHash = sha256Base64Url(canonicalJson([
      "liotan-device-directory-v1",
      second.statement,
      second.signature
    ]));
    const identityV2 = {
      ...identityV1,
      directory: {
        version: 2,
        hash: secondHash,
        statement: second.statement,
        signature: second.signature,
        firstContact: false
      },
      directoryLog: [{
        version: 2,
        previousHash: firstHash,
        hash: secondHash,
        statement: second.statement,
        signature: second.signature
      }]
    };
    await verifyAndPinAccountDirectory(engine, {
      username,
      identity: identityV2,
      deviceCommitments: [directoryDeviceCommitment(device)],
      allDevices: [device]
    });
    let rollbackRejected = false;
    let chainTamperRejected = false;
    try {
      await verifyAndPinAccountDirectory(engine, {
        username,
        identity: identityV1,
        deviceCommitments: [directoryDeviceCommitment(device)],
        allDevices: [device]
      });
    } catch { rollbackRejected = true; }
    try {
      await verifyAndPinAccountDirectory(engine, {
        username: `${username}-tampered`,
        identity: {
          ...identityV2,
          directoryLog: [{
            ...identityV2.directoryLog[0],
            previousHash: genesis
          }]
        },
        deviceCommitments: [directoryDeviceCommitment(device)],
        allDevices: [device]
      });
    } catch { chainTamperRejected = true; }
    const cleanUsername = `${username}-clean`;
    const clean = await verifyAndPinAccountDirectory(engine, {
      username: cleanUsername,
      identity: identityV2,
      deviceCommitments: [directoryDeviceCommitment(device)],
      allDevices: [device]
    });
    return {
      rollbackRejected,
      chainTamperRejected,
      cleanStatus: clean.status,
      cleanFirstContact: clean.firstContact,
      boundedTailAccepted: clean.directoryVersion === 2,
      latestVersion: identityV2.directory.version
    };
  } finally {
    Object.values(keys).forEach(value => value?.fill?.(0));
  }
};
window.runSyncCursorRepairProbe = function runSyncCursorRepairProbe() {
  const checkpoint = { processedSequence: 5, serverHead: 5 };
  const deleted = reconcileSyncCursor({ checkpoint, localHint: 0 });
  const ahead = reconcileSyncCursor({ checkpoint, localHint: 500 });
  const behind = reconcileSyncCursor({ checkpoint, localHint: 2 });
  const validPageHead = validateRecipientEventPage({
    after: 5,
    recipientHead: 9,
    events: [{ sequence: 7 }, { sequence: 9 }]
  });
  let reorderRejected = false;
  let rollbackRejected = false;
  try {
    validateRecipientEventPage({
      after: 5,
      recipientHead: 9,
      events: [{ sequence: 8 }, { sequence: 8 }]
    });
  } catch { reorderRejected = true; }
  try {
    reconcileSyncCursor({ checkpoint, localHint: 5, recipientHead: 4 });
  } catch { rollbackRejected = true; }
  return {
    deletedAfter: deleted.after,
    aheadAfter: ahead.after,
    behindAfter: behind.after,
    repairedAhead: ahead.repairedLocalHint,
    validPageHead,
    reorderRejected,
    rollbackRejected
  };
};
window.runLargeHistoryMigrationProbe = async function runLargeHistoryMigrationProbe() {
  const conversationId = `large-history-${crypto.randomUUID()}`;
  const cacheKey = randomBytes(32);
  const entries = Array.from({ length: 1000 }, (_, index) => {
    const sequence = index + 1;
    const clientMessageId = crypto.randomUUID();
    return {
      recordKey: `message:${conversationId}:${clientMessageId}`,
      value: {
        sequence,
        envelope: { clientMessageId, kind: "message", text: `migration-${sequence}` }
      }
    };
  });
  try {
    await putEncryptedRecords(entries, cacheKey, { batchSize: 64 });
    const startedAt = performance.now();
    let eventLoopTicks = 0;
    const responsivenessTimer = setInterval(() => { eventLoopTicks += 1; }, 50);
    const migration = await migrateEncryptedHistoryRecords(conversationId, cacheKey, { batchSize: 128 });
    clearInterval(responsivenessTimer);
    const latest = await listEncryptedHistoryRecords(conversationId, cacheKey, { limit: 3 });
    const legacy = await listEncryptedRecords(`message:${conversationId}:`, cacheKey);
    return {
      completed: migration.completed,
      written: migration.written,
      latest: latest.map(record => record.sequence),
      legacyRecords: legacy.length,
      eventLoopTicks,
      elapsedMs: performance.now() - startedAt
    };
  } finally {
    cacheKey.fill(0);
  }
};
window.getDatabaseRepairPolicy = () => ({
  unregisteredEarlyFailure: shouldAutomaticallyRepairDatabase("database-open", null),
  registeredEarlyFailure: shouldAutomaticallyRepairDatabase("database-open", { status: "active" }),
  unregisteredLateFailure: shouldAutomaticallyRepairDatabase("device-register", null)
});
window.getMlsMaintenancePolicy = () => ({
  selfUpdateHours: SELF_UPDATE_INTERVAL_MS / (60 * 60 * 1000),
  maintenanceSeconds: BACKGROUND_MAINTENANCE_INTERVAL_MS / 1000
});
window.runSafetyNumberProbe = () => {
  const participants = [
    { username: "alice", rootFingerprint: "root-a", directoryHash: "dir-a", directoryVersion: 4 },
    { username: "bob", rootFingerprint: "root-b", directoryHash: "dir-b", directoryVersion: 7 }
  ];
  const aliceView = computeSafetyNumber(participants);
  const bobView = computeSafetyNumber([...participants].reverse());
  const changed = computeSafetyNumber([
    participants[0],
    { ...participants[1], directoryHash: "dir-b-changed", directoryVersion: 8 }
  ]);
  return {
    sameAcrossSides: aliceView.fingerprint === bobView.fingerprint,
    deviceChangeDetected: aliceView.fingerprint !== changed.fingerprint,
    decimalGroups: aliceView.formatted.split(" ").length,
    qrBound: aliceView.qrPayload.endsWith(aliceView.fingerprint)
  };
};

window.runPersistentDatabaseProbe = async function runPersistentDatabaseProbe({ concurrentInit = false } = {}) {
  const name = `liotan-production-probe-${crypto.randomUUID()}`;
  const concurrentName = `${name}-parallel`;
  const keyBytes = randomBytes(32);
  const concurrentKeyBytes = randomBytes(32);
  try {
    if (!concurrentInit) await initializeCoreCryptoRuntime();
    const openAfterInit = async (databaseName, bytes) => {
      await initializeCoreCryptoRuntime();
      const key = new DatabaseKey(bytes);
      try {
        return await Database.open(databaseName, key);
      } finally {
        destroyUniffi(key);
      }
    };
    const [first, concurrent] = concurrentInit
      ? await Promise.all([
          openAfterInit(name, keyBytes),
          openAfterInit(concurrentName, concurrentKeyBytes)
        ])
      : [await openAfterInit(name, keyBytes), null];
    if (concurrent) {
      await concurrent.close();
      destroyUniffi(concurrent);
    }
    const memoryKey = new DatabaseKey(randomBytes(32));
    let memory;
    try {
      memory = await Database.inMemory(memoryKey);
    } finally {
      destroyUniffi(memoryKey);
    }
    const memoryCore = CoreCrypto.new(memory);
    destroyUniffi(memoryCore);
    await memory.close();
    destroyUniffi(memory);
    const firstLocation = await first.getLocation();
    destroyUniffi(CoreCrypto.new(first));
    await first.close();
    destroyUniffi(first);
    const reopened = await openAfterInit(name, keyBytes);
    const secondLocation = await reopened.getLocation();
    destroyUniffi(CoreCrypto.new(reopened));
    await reopened.close();
    destroyUniffi(reopened);
    return {
      ok: true,
      memoryCoreCreated: Boolean(memoryCore),
      firstLocation,
      secondLocation
    };
  } finally {
    keyBytes.fill(0);
    concurrentKeyBytes.fill(0);
    await deleteDatabase(name).catch(() => {});
    await deleteDatabase(concurrentName).catch(() => {});
  }
};

window.runMlsInterop = async function runMlsInterop() {
  await initializeCoreCryptoRuntime();
  const alice = await createMlsClient("00000000-0000-4000-8000-000000000001", "0000000000000001");
  const bob = await createMlsClient("00000000-0000-4000-8000-000000000002", "0000000000000002");
  const conversationId = new ConversationId(randomBytes(32));
  try {
    const bobPackage = await bob.core.transaction(ctx => ctx.generateKeyPackage(bob.credentialRef, 3600));
    await alice.core.transaction(ctx => ctx.createConversation(conversationId, alice.credentialRef));
    await alice.core.transaction(ctx => ctx.addClientsToConversation(conversationId, [bobPackage]));
    const addBundle = alice.commits.shift();
    if (!addBundle?.welcome) throw new Error("add commit did not produce Welcome");
    const welcome = new Welcome(addBundle.welcome.serialize());
    try {
      await bob.core.transaction(ctx => ctx.processWelcomeMessage(welcome));
    } finally {
      destroyUniffi(welcome);
    }
    destroyUniffi(bobPackage);
    const ciphertext = await alice.core.transaction(ctx => ctx.encryptMessage(conversationId, encoder.encode("production-mls")));
    if (await decryptText(bob, conversationId, ciphertext) !== "production-mls") throw new Error("MLS mismatch");
    const reply = await bob.core.transaction(ctx => ctx.encryptMessage(conversationId, encoder.encode("production-reply")));
    if (await decryptText(alice, conversationId, reply) !== "production-reply") throw new Error("MLS reply mismatch");
    const outOfOrderFirst = await alice.core.transaction(ctx => ctx.encryptMessage(conversationId, encoder.encode("out-of-order-first")));
    const outOfOrderSecond = await alice.core.transaction(ctx => ctx.encryptMessage(conversationId, encoder.encode("out-of-order-second")));
    const outOfOrderAccepted = await decryptText(bob, conversationId, outOfOrderSecond) === "out-of-order-second" &&
      await decryptText(bob, conversationId, outOfOrderFirst) === "out-of-order-first";
    const undeliveredPastEpoch = await alice.core.transaction(ctx =>
      ctx.encryptMessage(conversationId, encoder.encode("past-epoch-undelivered"))
    );
    const secondUndeliveredPastEpoch = await alice.core.transaction(ctx =>
      ctx.encryptMessage(conversationId, encoder.encode("past-epoch-second-probe"))
    );
    await alice.core.transaction(ctx => ctx.updateKeyingMaterial(conversationId));
    const updateBundle = alice.commits.shift();
    await bob.core.transaction(ctx => ctx.decryptMessage(conversationId, updateBundle.commit));
    let pastEpochOneBackAccepted = false;
    try {
      pastEpochOneBackAccepted = await decryptText(bob, conversationId, undeliveredPastEpoch) ===
        "past-epoch-undelivered";
    } catch {}
    await alice.core.transaction(ctx => ctx.updateKeyingMaterial(conversationId));
    const secondUpdateBundle = alice.commits.shift();
    await bob.core.transaction(ctx => ctx.decryptMessage(conversationId, secondUpdateBundle.commit));
    const epoch = Number(await alice.core.transaction(ctx => ctx.conversationEpoch(conversationId)));
    let pastEpochTwoBackAccepted = false;
    try {
      pastEpochTwoBackAccepted = await decryptText(bob, conversationId, secondUndeliveredPastEpoch) ===
        "past-epoch-second-probe";
    } catch {}
    const tamperTarget = await alice.core.transaction(ctx => ctx.encryptMessage(conversationId, encoder.encode("authenticated")));
    const tampered = new Uint8Array(tamperTarget);
    tampered[tampered.length - 1] ^= 1;
    let tamperRejected = false;
    try { await bob.core.transaction(ctx => ctx.decryptMessage(conversationId, tampered)); } catch { tamperRejected = true; }
    if (!tamperRejected || await decryptText(bob, conversationId, tamperTarget) !== "authenticated") {
      throw new Error("MLS tamper handling mismatch");
    }
    let replayRejected = false;
    try { await bob.core.transaction(ctx => ctx.decryptMessage(conversationId, tamperTarget)); } catch { replayRejected = true; }
    const rollbackEpoch = Number(await alice.core.transaction(ctx => ctx.conversationEpoch(conversationId)));
    const commitCountBeforeRollback = alice.commits.length;
    let transactionRejected = false;
    try {
      await alice.core.transaction(async ctx => {
        await ctx.updateKeyingMaterial(conversationId);
        throw new Error("intentional transaction rollback");
      });
    } catch { transactionRejected = true; }
    const transactionRollbackPreservedEpoch = transactionRejected &&
      Number(await alice.core.transaction(ctx => ctx.conversationEpoch(conversationId))) === rollbackEpoch;
    alice.commits.splice(commitCountBeforeRollback);
    await alice.core.transaction(ctx => ctx.removeClientsFromConversation(conversationId, [bob.clientId]));
    const removeBundle = alice.commits.shift();
    await bob.core.transaction(ctx => ctx.decryptMessage(conversationId, removeBundle.commit));
    const postRemoval = await alice.core.transaction(ctx =>
      ctx.encryptMessage(conversationId, encoder.encode("post-removal"))
    );
    let removedClientRejected = false;
    try { await bob.core.transaction(ctx => ctx.decryptMessage(conversationId, postRemoval)); }
    catch { removedClientRejected = true; }
    const roster = await alice.core.transaction(ctx => ctx.getClientIds(conversationId));
    return {
      ok: true,
      epoch,
      rosterSize: roster.length,
      tamperRejected,
      replayRejected,
      outOfOrderAccepted,
      pastEpochOneBackAccepted,
      pastEpochTwoBackAccepted,
      transactionRollbackPreservedEpoch,
      removedClientRejected
    };
  } finally {
    destroyUniffi(conversationId);
    await closeMlsClient(alice);
    await closeMlsClient(bob);
  }
};

function TransitionHarness() {
  const transition = useSecureTransition();
  useEffect(() => { transition.completeSecureTransition({ minimumMs: 0 }); }, []);

  async function run(kind) {
    if (kind === "logout") {
      transition.beginSecureTransition("closing-session", { minimumMs: 80 });
      await new Promise(resolve => setTimeout(resolve, 20));
      await transition.completeSecureTransition();
      return;
    }
    transition.beginSecureTransition("checking-session", { minimumMs: 100 });
    await new Promise(resolve => setTimeout(resolve, 20));
    transition.updateSecureTransition("opening-storage");
    await new Promise(resolve => setTimeout(resolve, 20));
    transition.updateSecureTransition("preparing-messages");
    await transition.completeSecureTransition();
  }

  return <>
    <button data-action="login" onClick={() => run("login")}>login</button>
    <button data-action="register" onClick={() => run("register")}>register</button>
    <button data-action="logout" onClick={() => run("logout")}>logout</button>
    <SecureTransitionGate active={transition.secureTransition.active} stage={transition.secureTransition.stage} />
  </>;
}

window.mountTransitionHarness = function mountTransitionHarness() {
  createRoot(document.querySelector("#root")).render(<TransitionHarness />);
};

window.mountFailingCryptoGate = function mountFailingCryptoGate() {
  const storageError = Object.assign(new Error("technical detail must not reach the user"), {
    code: "registered-storage-unavailable",
    reprovisionRequired: true
  });
  const services = {
    loadRecoveryKey: async () => "A".repeat(43),
    initializeMlsEngine: async () => { throw storageError; },
    cryptoBootstrap: async () => { throw new Error("unexpected bootstrap"); },
    createRecoveryKey: () => "",
    saveRecoveryKey: async () => {},
    normalizeRecoveryKey: () => ({ encoded: "", bytes: new Uint8Array(32) }),
    reprovisionMlsDevice: async () => {}
  };
  createRoot(document.querySelector("#root")).render(
    <CryptoGate username="fixture-user" cryptoServices={services} onBlocked={async () => {}}>
      <div id="messenger-sentinel">messenger must stay blocked</div>
    </CryptoGate>
  );
};

window.mountAttachmentPreview = function mountAttachmentPreview(kind = "file") {
  const item = kind === "file"
    ? {
        file: new File(["patch"], "release-fix.patch", { type: "text/plain" }),
        type: "file",
        url: "fixture-file",
        name: "release-fix.patch",
        size: 5,
        mimeType: "text/plain",
        width: 0,
        height: 0
      }
    : {
        file: new File([new Uint8Array(16)], "portrait.mp4", { type: "video/mp4" }),
        type: "video",
        url: "data:video/mp4;base64,",
        name: "portrait.mp4",
        size: 16,
        mimeType: "video/mp4",
        width: 720,
        height: 1280,
        orientation: "portrait"
      };
  createRoot(document.querySelector("#root")).render(
    <AttachmentDraftModal
      attachmentDraft={[item]}
      attachmentCaption=""
      setAttachmentCaption={() => {}}
      sendingDraft={false}
      onClose={() => {}}
      onRemove={() => {}}
      onSend={() => {}}
      onAddMore={() => {}}
      onMediaMeta={() => {}}
    />
  );
};

window.mountUserProfile = function mountUserProfile(user) {
  createRoot(document.querySelector("#root")).render(
    <UserProfileModal
      user={user}
      username="Alice"
      deleteGroupDialog={() => {}}
      updateGroup={() => {}}
      openUserProfile={() => {}}
      onClose={() => {}}
    />
  );
};

window.mountChatSecurityNotice = function mountChatSecurityNotice(ready) {
  createRoot(document.querySelector("#root")).render(<ChatSecurityNotice ready={Boolean(ready)} />);
};

function SafetyNumberHarness() {
  const [open, setOpen] = React.useState(true);
  const [verified, setVerified] = React.useState(false);
  if (!open) return <div id="safety-result">{verified ? "verified" : "closed"}</div>;
  return <SafetyNumberModal
    info={{
      qrPayload: "liotan-safety:v2:fixture-bound-payload",
      formatted: "12345 67890 12345 67890",
      verificationStatus: "first-seen",
      participants: [
        { username: "alice", rootFingerprint: "A".repeat(43), directoryVersion: 2 },
        { username: "bob", rootFingerprint: "B".repeat(43), directoryVersion: 4 }
      ]
    }}
    onClose={() => setOpen(false)}
    onVerify={async () => setVerified(true)}
  />;
}

window.mountSafetyNumber = function mountSafetyNumber() {
  createRoot(document.querySelector("#root")).render(<SafetyNumberHarness />);
};

window.mountCryptoDevices = function mountCryptoDevices() {
  const devices = [
    {
      deviceId: "0000000000000001",
      status: "active",
      activationMode: "initial",
      credentialThumbprint: "A".repeat(43),
      createdAt: "2026-01-01T00:00:00.000Z",
      lastSeenAt: "2026-01-02T00:00:00.000Z"
    },
    {
      deviceId: "0000000000000002",
      status: "pending",
      activationMode: "device-approval",
      credentialThumbprint: "B".repeat(43),
      createdAt: "2026-01-03T00:00:00.000Z",
      lastSeenAt: "2026-01-03T00:00:00.000Z"
    },
    {
      deviceId: "0000000000000003",
      status: "active",
      activationMode: "device-approval",
      credentialThumbprint: "C".repeat(43),
      createdAt: "2026-01-04T00:00:00.000Z",
      lastSeenAt: "2026-01-04T00:00:00.000Z"
    }
  ];
  let protectedRecovery = false;
  const cryptoServices = {
    currentDeviceId: () => devices[0].deviceId,
    listDevices: async () => ({ devices: [...devices] }),
    approveDevice: async deviceId => {
      const target = devices.find(device => device.deviceId === deviceId);
      target.status = "active";
      return { conversationsBlocked: 1 };
    },
    revokeDevice: async deviceId => {
      const target = devices.find(device => device.deviceId === deviceId);
      target.status = "revoked";
      return { conversationsBlocked: 2 };
    },
    getRecoveryProtectionStatus: async () => ({ configured: true, requiresUserPresence: protectedRecovery }),
    enableRecoveryProtection: async () => { protectedRecovery = true; },
    disableRecoveryProtection: async () => { protectedRecovery = false; }
  };
  const labels = {
    devices: "Устройства",
    thisDevice: "Это устройство",
    activeSessions: "Активные сессии",
    noDevices: "Нет устройств",
    noOtherDevices: "Нет других устройств",
    terminateOthers: "Завершить другие",
    restrictedSessionMessage: "Недоступно",
    current: "текущее",
    lastActive: "Последняя активность",
    disconnect: "Отключить",
    unknownDevice: "Неизвестное устройство"
  };
  createRoot(document.querySelector("#root")).render(<DevicesPage
    back={() => {}}
    state={{ username: "fixture-user", sessions: [] }}
    actions={{ revoke: async () => {}, logoutOthers: async () => {} }}
    labels={labels}
    cryptoServices={cryptoServices}
  />);
};

window.mountSettingsIcon = function mountSettingsIcon() {
  createRoot(document.querySelector("#root")).render(<LiotanIcon name="settings" size={48} title="Настройки" />);
};

document.querySelector("#status").textContent = "production-fixture-loaded";
