import {
  CipherSuite,
  ConversationId,
  CoreCrypto,
  Credential,
  Database,
  DatabaseKey,
  Welcome
} from "@wireapp/core-crypto/browser";
import { initializeCoreCryptoRuntime } from "../../src/crypto/coreCryptoRuntime";
import { createInitializedClientIdentity } from "../../src/crypto/mls/identifiers";
import { assertEnvelopeSchema } from "../../src/crypto/mls/envelope";
import { MEDIA_MAGIC } from "../../src/crypto/mls/constants";
import { destroyUniffi } from "../../src/crypto/mls/uniffiLifecycle";
import {
  createRecoveryKey,
  getEncryptedHistoryRecord,
  listEncryptedRecords,
  listEncryptedHistoryRecords,
  loadRecoveryKey,
  migrateEncryptedHistoryRecords,
  putEncryptedHistoryRecord,
  putEncryptedRecords,
  saveRecoveryKey
} from "../../src/crypto/recoveryStore";
import React, { useEffect } from "react";
import { createRoot } from "react-dom/client";
import CryptoGate from "../../src/crypto/CryptoGate";
import SecureTransitionGate from "../../src/crypto/SecureTransitionGate";
import AttachmentDraftModal from "../../src/components/chat/AttachmentDraftModal";
import UserProfileModal from "../../src/components/modals/UserProfileModal";
import ChatSecurityNotice from "../../src/components/chat/ChatSecurityNotice";
import LiotanIcon from "../../src/components/common/LiotanIcon";
import useSecureTransition from "../../src/hooks/useSecureTransition";
import { shouldAutomaticallyRepairDatabase } from "../../src/crypto/mls/databaseStorage";
import "../../src/App.css";

const SUITE = CipherSuite.Mls128Dhkemx25519Aes128gcmSha256Ed25519;
const WASM_URL = new URL(
  "../../node_modules/@wireapp/core-crypto/dist/browser/autogenerated/wasm-bindgen/index_bg.wasm",
  import.meta.url
).href;
const encoder = new TextEncoder();
const decoder = new TextDecoder();

function randomBytes(length) {
  return crypto.getRandomValues(new Uint8Array(length));
}

function deleteDatabase(name) {
  return new Promise((resolve, reject) => {
    const request = indexedDB.deleteDatabase(name);
    request.onsuccess = () => resolve();
    request.onerror = () => reject(request.error || new Error("database deletion failed"));
    request.onblocked = () => reject(new Error("database deletion blocked"));
  });
}

async function createMlsClient(uuid, deviceHex) {
  const databaseKey = new DatabaseKey(randomBytes(32));
  let database;
  try {
    database = await Database.inMemory(databaseKey);
  } finally {
    destroyUniffi(databaseKey);
  }
  const core = CoreCrypto.new(database);
  const { clientId } = await createInitializedClientIdentity({
    cryptoUserId: uuid,
    deviceId: deviceHex,
    domain: "browser.test.invalid"
  });
  const commits = [];
  const transport = {
    async sendCommitBundle(bundle) { commits.push(bundle); },
    async prepareForTransport() { throw new Error("history-secret transport must stay disabled"); }
  };
  await core.transaction(ctx => ctx.mlsInit(clientId, transport));
  const credential = Credential.basic(SUITE, clientId);
  let credentialRef;
  try {
    credentialRef = await core.transaction(ctx => ctx.addCredential(credential));
  } finally {
    destroyUniffi(credential);
  }
  return { database, core, clientId, credentialRef, commits };
}

async function closeMlsClient(client) {
  destroyUniffi(client.credentialRef);
  destroyUniffi(client.clientId);
  destroyUniffi(client.core);
  await client.database.close();
  destroyUniffi(client.database);
}

async function decryptText(client, conversationId, ciphertext) {
  const result = await client.core.transaction(ctx => ctx.decryptMessage(conversationId, ciphertext));
  return decoder.decode(result.message);
}

window.getProductionWasmUrl = () => WASM_URL;
window.runColdStartClientIdentityProbe = async function runColdStartClientIdentityProbe() {
  const expected = "00000000-0000-4000-8000-000000000009:0000000000000009@browser.test.invalid";
  const identity = await createInitializedClientIdentity({
    cryptoUserId: "00000000-0000-4000-8000-000000000009",
    deviceId: "0000000000000009",
    domain: "browser.test.invalid"
  });
  try {
    return { ok: true, clientId: identity.clientIdString, matches: identity.clientIdString === expected };
  } finally {
    destroyUniffi(identity.clientId);
  }
};
window.createProductionRecoveryKey = () => createRecoveryKey();
window.saveProductionRecoveryKey = (username, key) => saveRecoveryKey(username, key);
window.loadProductionRecoveryKey = username => loadRecoveryKey(username);
window.runEncryptedHistoryPagingProbe = async function runEncryptedHistoryPagingProbe() {
  const conversationId = `history-${crypto.randomUUID()}`;
  const cacheKey = randomBytes(32);
  try {
    for (let sequence = 1; sequence <= 5; sequence += 1) {
      const clientMessageId = `00000000-0000-4000-8000-${String(sequence).padStart(12, "0")}`;
      await putEncryptedHistoryRecord({ conversationId, sequence, clientMessageId }, {
        sequence,
        envelope: { clientMessageId, kind: "message", text: `message-${sequence}` }
      }, cacheKey);
    }
    const latest = await listEncryptedHistoryRecords(conversationId, cacheKey, { limit: 2 });
    const older = await listEncryptedHistoryRecords(conversationId, cacheKey, { beforeSequence: 4, limit: 2 });
    const newer = await listEncryptedHistoryRecords(conversationId, cacheKey, { afterSequence: 2, limit: 2 });
    const exactId = "00000000-0000-4000-8000-000000000004";
    const exact = await getEncryptedHistoryRecord(conversationId, exactId, cacheKey);
    return {
      latest: latest.map(record => record.sequence),
      older: older.map(record => record.sequence),
      newer: newer.map(record => record.sequence),
      exact: exact?.sequence || 0
    };
  } finally {
    cacheKey.fill(0);
  }
};
window.runAdaptiveMediaDescriptorProbe = function runAdaptiveMediaDescriptorProbe() {
  const accepted = [];
  for (const chunkSize of [256 * 1024, 512 * 1024, 1024 * 1024]) {
    const originalSize = chunkSize + 1;
    const chunks = 2;
    const messageId = crypto.randomUUID();
    const envelope = {
      v: 1,
      kind: "message",
      conversationId: crypto.randomUUID(),
      clientMessageId: messageId,
      senderUsername: "fixture-user",
      senderClientId: "fixture-client@example.test",
      sentAt: new Date().toISOString(),
      text: "",
      attachment: {
        v: 1,
        conversationId: "",
        messageId,
        uploadId: "A".repeat(24),
        bindingId: "B".repeat(24),
        ciphertextHash: "C".repeat(43),
        key: "D".repeat(43),
        noncePrefix: "E".repeat(11),
        chunkSize,
        chunks,
        ciphertextBytes: MEDIA_MAGIC.length + chunks * (chunkSize + 16),
        original: {
          name: "fixture.bin",
          type: "file",
          mimeType: "application/octet-stream",
          size: originalSize,
          duration: 0,
          waveform: [],
          width: 0,
          height: 0
        }
      },
      replyTo: null
    };
    envelope.attachment.conversationId = envelope.conversationId;
    assertEnvelopeSchema(envelope);
    accepted.push(chunkSize);
  }
  return accepted;
};
window.runLargeHistoryMigrationProbe = async function runLargeHistoryMigrationProbe() {
  const conversationId = `large-history-${crypto.randomUUID()}`;
  const cacheKey = randomBytes(32);
  const entries = Array.from({ length: 1000 }, (_, index) => {
    const sequence = index + 1;
    const clientMessageId = crypto.randomUUID();
    return {
      recordKey: `message:${conversationId}:${clientMessageId}`,
      value: {
        sequence,
        envelope: { clientMessageId, kind: "message", text: `migration-${sequence}` }
      }
    };
  });
  try {
    await putEncryptedRecords(entries, cacheKey, { batchSize: 64 });
    const startedAt = performance.now();
    let eventLoopTicks = 0;
    const responsivenessTimer = setInterval(() => { eventLoopTicks += 1; }, 50);
    const migration = await migrateEncryptedHistoryRecords(conversationId, cacheKey, { batchSize: 128 });
    clearInterval(responsivenessTimer);
    const latest = await listEncryptedHistoryRecords(conversationId, cacheKey, { limit: 3 });
    const legacy = await listEncryptedRecords(`message:${conversationId}:`, cacheKey);
    return {
      completed: migration.completed,
      written: migration.written,
      latest: latest.map(record => record.sequence),
      legacyRecords: legacy.length,
      eventLoopTicks,
      elapsedMs: performance.now() - startedAt
    };
  } finally {
    cacheKey.fill(0);
  }
};
window.getDatabaseRepairPolicy = () => ({
  unregisteredEarlyFailure: shouldAutomaticallyRepairDatabase("database-open", null),
  registeredEarlyFailure: shouldAutomaticallyRepairDatabase("database-open", { status: "active" }),
  unregisteredLateFailure: shouldAutomaticallyRepairDatabase("device-register", null)
});

window.runPersistentDatabaseProbe = async function runPersistentDatabaseProbe({ concurrentInit = false } = {}) {
  const name = `liotan-production-probe-${crypto.randomUUID()}`;
  const concurrentName = `${name}-parallel`;
  const keyBytes = randomBytes(32);
  const concurrentKeyBytes = randomBytes(32);
  try {
    if (!concurrentInit) await initializeCoreCryptoRuntime();
    const openAfterInit = async (databaseName, bytes) => {
      await initializeCoreCryptoRuntime();
      const key = new DatabaseKey(bytes);
      try {
        return await Database.open(databaseName, key);
      } finally {
        destroyUniffi(key);
      }
    };
    const [first, concurrent] = concurrentInit
      ? await Promise.all([
          openAfterInit(name, keyBytes),
          openAfterInit(concurrentName, concurrentKeyBytes)
        ])
      : [await openAfterInit(name, keyBytes), null];
    if (concurrent) {
      await concurrent.close();
      destroyUniffi(concurrent);
    }
    const memoryKey = new DatabaseKey(randomBytes(32));
    let memory;
    try {
      memory = await Database.inMemory(memoryKey);
    } finally {
      destroyUniffi(memoryKey);
    }
    const memoryCore = CoreCrypto.new(memory);
    destroyUniffi(memoryCore);
    await memory.close();
    destroyUniffi(memory);
    const firstLocation = await first.getLocation();
    destroyUniffi(CoreCrypto.new(first));
    await first.close();
    destroyUniffi(first);
    const reopened = await openAfterInit(name, keyBytes);
    const secondLocation = await reopened.getLocation();
    destroyUniffi(CoreCrypto.new(reopened));
    await reopened.close();
    destroyUniffi(reopened);
    return {
      ok: true,
      memoryCoreCreated: Boolean(memoryCore),
      firstLocation,
      secondLocation
    };
  } finally {
    keyBytes.fill(0);
    concurrentKeyBytes.fill(0);
    await deleteDatabase(name).catch(() => {});
    await deleteDatabase(concurrentName).catch(() => {});
  }
};

window.runMlsInterop = async function runMlsInterop() {
  await initializeCoreCryptoRuntime();
  const alice = await createMlsClient("00000000-0000-4000-8000-000000000001", "0000000000000001");
  const bob = await createMlsClient("00000000-0000-4000-8000-000000000002", "0000000000000002");
  const conversationId = new ConversationId(randomBytes(32));
  try {
    const bobPackage = await bob.core.transaction(ctx => ctx.generateKeyPackage(bob.credentialRef, 3600));
    await alice.core.transaction(ctx => ctx.createConversation(conversationId, alice.credentialRef));
    await alice.core.transaction(ctx => ctx.addClientsToConversation(conversationId, [bobPackage]));
    const addBundle = alice.commits.shift();
    if (!addBundle?.welcome) throw new Error("add commit did not produce Welcome");
    const welcome = new Welcome(addBundle.welcome.serialize());
    try {
      await bob.core.transaction(ctx => ctx.processWelcomeMessage(welcome));
    } finally {
      destroyUniffi(welcome);
    }
    destroyUniffi(bobPackage);
    const ciphertext = await alice.core.transaction(ctx => ctx.encryptMessage(conversationId, encoder.encode("production-mls")));
    if (await decryptText(bob, conversationId, ciphertext) !== "production-mls") throw new Error("MLS mismatch");
    const reply = await bob.core.transaction(ctx => ctx.encryptMessage(conversationId, encoder.encode("production-reply")));
    if (await decryptText(alice, conversationId, reply) !== "production-reply") throw new Error("MLS reply mismatch");
    await alice.core.transaction(ctx => ctx.updateKeyingMaterial(conversationId));
    const updateBundle = alice.commits.shift();
    await bob.core.transaction(ctx => ctx.decryptMessage(conversationId, updateBundle.commit));
    const epoch = Number(await alice.core.transaction(ctx => ctx.conversationEpoch(conversationId)));
    const tamperTarget = await alice.core.transaction(ctx => ctx.encryptMessage(conversationId, encoder.encode("authenticated")));
    const tampered = new Uint8Array(tamperTarget);
    tampered[tampered.length - 1] ^= 1;
    let tamperRejected = false;
    try { await bob.core.transaction(ctx => ctx.decryptMessage(conversationId, tampered)); } catch { tamperRejected = true; }
    if (!tamperRejected || await decryptText(bob, conversationId, tamperTarget) !== "authenticated") {
      throw new Error("MLS tamper handling mismatch");
    }
    let replayRejected = false;
    try { await bob.core.transaction(ctx => ctx.decryptMessage(conversationId, tamperTarget)); } catch { replayRejected = true; }
    const roster = await alice.core.transaction(ctx => ctx.getClientIds(conversationId));
    return { ok: true, epoch, rosterSize: roster.length, tamperRejected, replayRejected };
  } finally {
    destroyUniffi(conversationId);
    await closeMlsClient(alice);
    await closeMlsClient(bob);
  }
};

function TransitionHarness() {
  const transition = useSecureTransition();
  useEffect(() => { transition.completeSecureTransition({ minimumMs: 0 }); }, []);

  async function run(kind) {
    if (kind === "logout") {
      transition.beginSecureTransition("closing-session", { minimumMs: 80 });
      await new Promise(resolve => setTimeout(resolve, 20));
      await transition.completeSecureTransition();
      return;
    }
    transition.beginSecureTransition("checking-session", { minimumMs: 100 });
    await new Promise(resolve => setTimeout(resolve, 20));
    transition.updateSecureTransition("opening-storage");
    await new Promise(resolve => setTimeout(resolve, 20));
    transition.updateSecureTransition("preparing-messages");
    await transition.completeSecureTransition();
  }

  return <>
    <button data-action="login" onClick={() => run("login")}>login</button>
    <button data-action="register" onClick={() => run("register")}>register</button>
    <button data-action="logout" onClick={() => run("logout")}>logout</button>
    <SecureTransitionGate active={transition.secureTransition.active} stage={transition.secureTransition.stage} />
  </>;
}

window.mountTransitionHarness = function mountTransitionHarness() {
  createRoot(document.querySelector("#root")).render(<TransitionHarness />);
};

window.mountFailingCryptoGate = function mountFailingCryptoGate() {
  const storageError = Object.assign(new Error("technical detail must not reach the user"), {
    code: "registered-storage-unavailable",
    reprovisionRequired: true
  });
  const services = {
    loadRecoveryKey: async () => "A".repeat(43),
    initializeMlsEngine: async () => { throw storageError; },
    cryptoBootstrap: async () => { throw new Error("unexpected bootstrap"); },
    createRecoveryKey: () => "",
    saveRecoveryKey: async () => {},
    normalizeRecoveryKey: () => ({ encoded: "", bytes: new Uint8Array(32) }),
    reprovisionMlsDevice: async () => {}
  };
  createRoot(document.querySelector("#root")).render(
    <CryptoGate username="fixture-user" cryptoServices={services} onBlocked={async () => {}}>
      <div id="messenger-sentinel">messenger must stay blocked</div>
    </CryptoGate>
  );
};

window.mountAttachmentPreview = function mountAttachmentPreview(kind = "file") {
  const item = kind === "file"
    ? {
        file: new File(["patch"], "release-fix.patch", { type: "text/plain" }),
        type: "file",
        url: "fixture-file",
        name: "release-fix.patch",
        size: 5,
        mimeType: "text/plain",
        width: 0,
        height: 0
      }
    : {
        file: new File([new Uint8Array(16)], "portrait.mp4", { type: "video/mp4" }),
        type: "video",
        url: "data:video/mp4;base64,",
        name: "portrait.mp4",
        size: 16,
        mimeType: "video/mp4",
        width: 720,
        height: 1280,
        orientation: "portrait"
      };
  createRoot(document.querySelector("#root")).render(
    <AttachmentDraftModal
      attachmentDraft={[item]}
      attachmentCaption=""
      setAttachmentCaption={() => {}}
      sendingDraft={false}
      onClose={() => {}}
      onRemove={() => {}}
      onSend={() => {}}
      onAddMore={() => {}}
      onMediaMeta={() => {}}
    />
  );
};

window.mountUserProfile = function mountUserProfile(user) {
  createRoot(document.querySelector("#root")).render(
    <UserProfileModal
      user={user}
      username="Alice"
      deleteGroupDialog={() => {}}
      updateGroup={() => {}}
      openUserProfile={() => {}}
      onClose={() => {}}
    />
  );
};

window.mountChatSecurityNotice = function mountChatSecurityNotice(ready) {
  createRoot(document.querySelector("#root")).render(<ChatSecurityNotice ready={Boolean(ready)} />);
};

window.mountSettingsIcon = function mountSettingsIcon() {
  createRoot(document.querySelector("#root")).render(<LiotanIcon name="settings" size={48} title="Настройки" />);
};

document.querySelector("#status").textContent = "production-fixture-loaded";
